# Generated by Django 4.1.2 on 2022-10-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Debito', 'Debito'), ('Boleto', 'Boleto'), ('Financiamento', 'Financiamento'), ('Credito', 'Credito'), ('Recebimento Emprestimo', 'Emprestimo'), ('Vendas', 'Vendas'), ('Recebimento TED', 'Ted'), ('Recebimento DOC', 'Doc'), ('Aluguel', 'Aluguel')], max_length=50)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('cpf', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=64)),
                ('time', models.TimeField()),
                ('store_owner', models.CharField(max_length=248)),
                ('store_name', models.CharField(max_length=248)),
            ],
        ),
    ]
